
services:
  temporal-dev-server:
    build:
      context: .
      dockerfile: Dockerfile.temporal
    ports:
      - "7233:7233"
      - "8233:8233"
  transmission-endpoint:
    container_name: distributed_systems_example-transmission-endpoint
    build:
      context: .
      dockerfile: Dockerfile.transmissionEndpoint
    ports:
      - 3001:3000
  db: 
    container_name: distributed_systems_example-db
    image: postgres:16-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
  worker:
    container_name: distributed_systems_example-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - temporal-dev-server
  server:
    container_name: distributed_systems_example-server
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - temporal-dev-server
    ports:
      - 3002:3000
volumes:
  postgres_data:
