
services:
  temporal-dev-server:
    image: debian:buster
    command: >
      bash -c '\
        apt update && \
        apt install -y curl && \
        curl -sSf https://temporal.download/cli.sh | sh && \
        PATH="\$PATH:/root/.temporalio/bin" >> ~/.bashrc && \
        source ~/.bashrc && \
        temporal server start-dev
      '
  transmission-endpoint:
    container_name: distributed_systems_example-transmission-endpoint
    build:
      context: .
      dockerfile: Dockerfile.transmissionEndpoint
    ports:
      - 3001:3000
  db: 
    container_name: distributed_systems_example-db
    image: postgres:16-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
  worker:
    container_name: distributed_systems_example-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
  server:
    container_name: distributed_systems_example-server
    build:
      context: .
      dockerfile: Dockerfile.server
volumes:
  postgres_data:
