
services:
  temporal-dev-server:
    image: debian:buster
    command: >
      bash -c '\
        apt update && \
        apt install -y curl && \
        curl -sSf https://temporal.download/cli.sh | sh && \
        PATH="\$PATH:/root/.temporalio/bin" >> ~/.bashrc && \
        source ~/.bashrc && \
        temporal server start-dev --ip 0.0.0.0
      '
    ports:
      - 7233:7233
      - 8233:8233
  transmission-endpoint:
    container_name: distributed_systems_example-transmission-endpoint
    build:
      context: .
      dockerfile: Dockerfile.transmissionEndpoint
    ports:
      - 3001:3000
  db: 
    container_name: distributed_systems_example-db
    image: postgres:16-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
  worker:
    container_name: distributed_systems_example-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - temporal-dev-server
    restart: always
    environment:
      TEMPORAL_HOST_PORT: temporal-dev-server:7233
  server:
    container_name: distributed_systems_example-server
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - temporal-dev-server
    restart: always
    environment:
      TEMPORAL_HOST_PORT: temporal-dev-server:7233
    ports:
      - 3000:3000
volumes:
  postgres_data:
