FROM node:20 as lambda

ARG PORT=8000
ENV PORT=$PORT
WORKDIR /usr/src
COPY lambdas lambdas

RUN apt-get update
RUN apt-get install zip

RUN cd lambdas \
  # && npm install \
  && zip -r lambdas.zip .

FROM localstack/localstack
COPY --from=lambda /usr/src/lambdas/lambdas.zip ./lambdas.zip
